### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by VincentHoorpah** [tfriedel6/canvas#12]
Hi,

Do you have an option to apply an anti-aliasing filter (like described here: https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing)?

I'm just trying to display a rectangle like the white line below:
![anti_alias](https://user-images.githubusercontent.com/2055847/48935625-8bdb9300-ef08-11e8-9f19-fdef4a313009.png)

It can be seen here that there is no sufficient anti-aliasing.

Thank you !

**Comment by tfriedel6** [comment]
Hi,

by default multisampling (MSAA) is enabled by the sdlcanvas and glfwcanvas packages. I can see in the screenshot that there is some anti-aliasing going on, but yes it could still be nicer. 

If performance is not too much of an issue, one option is to use an offscreen canvas (using NewOffscreen) to render to at a higher resolution. After that you can render the offscreen canvas to the onscreen canvas by passing the canvas to DrawImage. This should produce supersampling AA.

Hope that helps

**Comment by VincentHoorpah** [comment]
Hi,

Do you have an example on how to create an offscreen canvas without any SDL or GLFW window ? 
Thanks

**Comment by tfriedel6** [comment]
Hi,

unfortunately as far as I know this is not possible, since the creation of an OpenGL context requires a window to render to, even if you never actually render to it. There seems to be an OpenGL extension for Linux that might make it work without a window, but no cross platform way that I can find. 

It might also be possible to create a window with SDL that will not be visible, maybe a 0x0 pixel borderless window. But of course that feels like a rather ugly hack.
