### ISSUE TITLE
Memory Leak in DrawImage()

### ISSUE THREAD

**Issue by deluan** [tfriedel6/canvas#19]
If I leave the code bellow running for a while, I can see it has a memory leak... If I replace the DrawImage call with PutImageData, the leakage goes away. It happens with when using `glfwcanvas` and `sdlcanvas`. 

OS: macOS Mohave
OpenGL: native? (didn't have to install anything)
SDL installed with `brew install sdl2`

```
package main

import (
	"image"
	"image/color"
	"math/rand"
	"time"

	"github.com/tfriedel6/canvas/glfwcanvas"
)

var (
	first = true
	bla   = time.Now()
	limg  *image.RGBA
)

func clientScreen() (image.Image, int64) {
	if !first && rand.Float64() < 0.99 {
		return limg, bla.UnixNano()
	}
	first = false
	rgba := image.NewRGBA(image.Rect(0, 0, 800, 800))
	for y := 0; y < 800; y++ {
		for x := 0; x < 800; x++ {
			rgba.Set(x, y, color.RGBA{
				R: byte(rand.Intn(256)),
				G: byte(rand.Intn(256)),
				B: byte(rand.Intn(256)),
				A: 255,
			})
		}
	}
	bla = time.Now()
	limg = rgba
	return rgba, bla.UnixNano()
}

func main() {
	win, cv, err := glfwcanvas.CreateWindow(800, 800, "hello")
	if err != nil {
		panic(err)
	}
	var lastRefresh int64
	win.MainLoop(func() {
		// This call returns a new image and the last timestamp it was updated
		img, lastUpdate := clientScreen()

		// If there were no changes, terminate loop
		if lastRefresh == lastUpdate {
			return
		}

		// Process screen updates
		// cv.PutImageData(img.(*image.RGBA), 0, 0)
		cv.DrawImage(img, 0, 0)
		lastRefresh = lastUpdate
	})
}
```

**Comment by tfriedel6** [comment]
This one is unfortunately (probably) hard to avoid, at least I can't think of a good way to avoid it. 

The way this works is that the DrawImage function will (when using OpenGL) allocate a texture and load the image into it. To delete the texture, the Image type actually has a `Delete` function on it, but as a safety catch there is also a finalizer so that the texture will be deleted if the garbage collector clears the image. 

This is not ideal, but my reasoning was that it makes it really easy to just call DrawImage with an image, and you don't have to worry about anything more in most cases. But in this kind of case it does cause a lot of memory use.

What you can also do is something like this:

```
var cvimg *canvas.Image
if cvimg == nil {
	cvimg, _ = cv.LoadImage(img)
} else {
	cvimg.Replace(img)
}
```

The `Replace` function will actually replace the texture and should not increase the memory usage.

Hope that helps, but I'm also open to suggestions for how to do this in a better way.
