### ISSUE TITLE
What's the proper way to use RGBA for something like SetFillStyle?

### ISSUE THREAD

**Issue by InterwebCounty** [tfriedel6/canvas#27]
Every thing I've tried (while studying the parseColor function, line 83 color.go) it chokes on the Alpha number.

I can't quite figure out what type it expects for that fourth value.  

I would love to just send it a string like SetFillStyle("rgba(240, 236, 206, .5)") and it looks like it's supposed to be able to do that, but it doesn't seem to work.  

Sending it a string like "rgb(240, 236, 206)" DOES work, so I'm thinking there might be a problem with line 209 on color.go.

I don't know if it's a bug or if I'm just stupid.

**Comment by tfriedel6** [comment]
Hi, sorry for the late reply, have been busy lately.

You're right, the rgba format doesn't get parsed according to the standard at the moment. It does work currently if you use rgba(240, 236, 206, 128), since the alpha component is just interpreted as a byte as well, not a zero to one floating point. I just didn't realize that the web standard uses that format. Then I guess I will change it to conform to the web standard.

**Comment by InterwebCounty** [comment]
I'm getting by with RGB and just using SetGlobalAlpha when I need transparency, seems like a good enough workaround.
