### ISSUE TITLE
Zoom / Magnify + MouseWheel

### ISSUE THREAD

**Issue by 5k3105** [tfriedel6/canvas#6]
Hi,
Based on your event example -- project at: https://github.com/5k3105/tilemap3

Updated sdlcanvas to include MouseWheelEvent:
```go
	MouseWheel func(x, y int)
...
		case *sdl.MouseWheelEvent:
			if wnd.MouseWheel != nil {
					wnd.MouseWheel(int(e.X), int(e.Y))
					handled = true
			}
```
then included it in project:
```go
	wnd.MouseWheel = func(x, y int) {
		action = 1
		if y == 1 {
			cscale /= cmultiplier
		}
		if y == -1 {
			cscale *= cmultiplier
		}
		cv.Scale(cscale, cscale)
		println("y:  ", y)
	}
```
this does zoom (my code is buggy..) what I've drawn with lines but the Images (from PutImageData) are not zoomed. I believe this is by design based on this article: https://stackoverflow.com/questions/3420975/html5-canvas-zooming#3422425

Is it possible to include a function which scales the whole canvas/window?

**Comment by tfriedel6** [comment]
Hi!

Such a function would make sense, since the HTML canvas also lets you define both an internal size and a display size, which this package is missing. I'll have to think about where to put that. I would not recommend this for zooming though, since it would mean that the image would be rendered at a huge or tiny resolution internally and then scaled to the window size.

Instead of using PutImageData, you could also use DrawImage:
`cv.DrawImage("u2_"+t.Type+".pcx", float64(t.X), float64(t.Y))`

This will load the pcx file (which can be decoded after importing the pcx package), and the canvas library will cache the image. Or you can use the explicit canvas.LoadImage function.

I like the MouseWheel callback btw, will add that.

**Comment by 5k3105** [comment]
https://github.com/5k3105/tilemap4

```
λ .\tilemap4.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x100 pc=0x4d9e22]

goroutine 1 [running, locked to thread]:
github.com/tfriedel6/canvas.loadImageRGBA(0xc042050100, 0x4b49ce, 0xc042058340, 0x0)
        C:/Users/clott/go/src/github.com/tfriedel6/canvas/images.go:107 +0xd2
github.com/tfriedel6/canvas.LoadImage(0x5a2620, 0xc042050100, 0x5e1f40, 0xc042050100, 0x0)
        C:/Users/clott/go/src/github.com/tfriedel6/canvas/images.go:31 +0x574
main.init.0()
        C:/Users/clott/go/src/github.com/5k3105/tilemap4/main.go:41 +0x2ac
```

DrawImage does work, but if I try to LoadImage with the decoded image I get the above error. If I try to LoadImage with the filename I get:
```failed to load image: Unsupported source type```

In both instances I do have the pcx library imported.

**Comment by 5k3105** [comment]
I've updated to load file after ```sdlcanvas.CreateWindow``` : https://github.com/5k3105/tilemap4

The reason why I got ```failed to load image: Unsupported source type``` was I passed a file handle instead of the file string. My mistake :D

Zoom works mostly. I need to check why the mouse cursor does not track correctly.

Thanks!
