### ISSUE TITLE
Lines remain on canvas after screen clear

### ISSUE THREAD

**Issue by 5k3105** [tfriedel6/canvas#7]
Example both here: https://github.com/5k3105/slowdraw1 and here: https://github.com/5k3105/tilemap4

Artifacts remain on screen after scale/clear/redraw. This is windows 7.

**Comment by tfriedel6** [comment]
I can't see what's wrong with the slowdraw1 example, but in tilemap4 I can see the lines remaining when scaling with the mouse wheel. But that's because the FillRect call is also scaled, so it doesn't actually draw over everything. 

What you would have to do is do the FillRect call before the Scale and Translate calls. Also, transformations (like Scale and Translate) are cumulative, so if you call Scale(0.5, 0.5) twice, you get the same as calling Scale(0.25, 0.25). This also works across frames. So what you have to do is call Save() before doing the transformations, then Restore() after all the drawing (or use defer).

Hope that helps

**Comment by 5k3105** [comment]
I moved the 'clear screen' to the top like you said and that fixed it (https://github.com/5k3105/tilemap5).
Still see line drawn beneath on slowdraw (https://github.com/5k3105/slowdraw2).
Are you also using win7?

**Comment by tfriedel6** [comment]
I tried it under Linux and Win10 and it looks the same, but I don't have a Win7 installation to test on. 

But I'm not sure what I should be seeing. At the moment there is a square being drawn from the top and bottom centers toward the side centers. Just before the square closes, it all gets cleared and starts over. Is that correct?

**Comment by 5k3105** [comment]
Yes. But I continue to see a square beneath - it doesn't seem to clear. If it works on win10 I will assume it's something particular with my machine. Thanks!
