### ISSUE TITLE
[suggestion] Video support?

### ISSUE THREAD

**Issue by SuperDog83** [tfriedel6/canvas#9]
Hello,
I think it would be great if this lib had some way to play a video on the canvas. Maybe something like in HTML5 Canvas where you can drawImage a video, or something even better w/ sound support?
Thoughts?

**Comment by tfriedel6** [comment]
Hi, 
that would certainly be great if DrawImage could also draw a video frame. I don't want to add a dependency to a video library, but what would solve it quite nicely is if DrawImage could also take an interface of some kind. Do you happen to know any decent video libraries? I played around with a Go binding for ffmpeg once, but couldn't get it to work.

**Comment by SuperDog83** [comment]
@tfriedel6 did you check out https://github.com/3d0c/gmf ? ffmpeg bindings, seems to be still maintened, haven't tested it though, found it on awesome-go (https://github.com/avelino/awesome-go#video)

**Comment by tfriedel6** [comment]
Hi! I didn't have much time last week, but I gave it a shot just now to see what could be done. The best I could come up with was to add a Replace function to the Image type, so that you can replace the image every frame and avoid allocating a new texture. I also tried the gmf library you linked, which seems to work better than any I tried before, but I don't know enough to be able to use it correctly.

Anyway, here is a gist that is just a modification of one of their examples and seems to be able to basically display a video, though it does not respect the frame rate. Not sure how to do that.
https://gist.github.com/tfriedel6/be453334bd025ded790b5d11ea584ca2
